spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gateway
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    jpa:
      #指定数据库
      database: mysql
      #打印sql
      show-sql: true
      hibernate:
        #开启数据库更新表
        ddl-auto: update
        #指定命名策略
        naming:
          strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          #Hibernate方言
          dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: spring-cloud-gateway-sample
  cloud:
    gateway:
      routes:
        - id: baidu
          uri: https://www.baidu.com/
          predicates:
            # 匹配路径转发
            - Path=/baidu
#        - id: jd
#          uri: https://www.jd.com/
#          predicates:
#            # 匹配路径转发
#            - Path=/jd
# 端口号
server:
  port: 9090
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always